version: "3.9"

services:
#  db_fc:
#    image: postgres:latest
#    container_name: db_fc
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: rad_elements
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    command: postgres -c listen_addresses='*'
##    env_file:
##      - .env
  django-app:
    build:
#      dockerfile: djsite/Dockerfile
      context: .
    ports:
      - "8000:8000"