# Generated by Django 4.2.13 on 2024-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rstring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedvideo",
            name="text_request",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
